# Generated by Django 4.0.3 on 2022-03-20 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_lead_assigne_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='assigne_to',
            new_name='assigned_to',
        ),
    ]
