# Generated by Django 4.0.3 on 2022-03-20 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='members',
            new_name='agents',
        ),
    ]
