# Generated by Django 4.0.3 on 2022-03-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annunci', '0002_remove_annunci_priority_annunci_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annunci',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='annunci',
            name='civico',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='annunci',
            name='comune',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='annunci',
            name='descrizione',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='annunci',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='annunci',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='annunci',
            name='prezzo_due',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='annunci',
            name='prezzo_quattro',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='annunci',
            name='prezzo_tre',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='annunci',
            name='prezzo_uno',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='annunci',
            name='provincia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='annunci',
            name='quality',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='annunci',
            name='regione',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='annunci',
            name='zip_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='annunci',
            name='zona',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
