# Generated by Django 4.0.3 on 2022-04-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='website',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='phone',
            new_name='phone1',
        ),
        migrations.AddField(
            model_name='client',
            name='civico',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='comune',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='provincia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='regione',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Attivo'), ('suspended', 'Sospeso'), ('expired', 'Scaduto')], default='active', max_length=25),
        ),
        migrations.AddField(
            model_name='client',
            name='surname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='title',
            field=models.CharField(choices=[('signore', 'signore'), ('signora', 'signora'), ('dottore', 'dottore'), ('dottoressa', 'dottoressa'), ('geometra', 'geometra')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('cliente', 'In asta'), ('investitore', 'Investitore'), ('proprietario', 'Proprietario')], default='cliente', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='zip_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='zona',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_person',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
