# Generated by Django 4.0.3 on 2022-04-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rename_website_client_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='title',
            field=models.CharField(choices=[('signore', 'Sig.'), ('signora', 'Sig.ra'), ('dottore', 'Dott.'), ('dottoressa', 'Dott.ssa'), ('geometra', 'Geom.')], default='', max_length=255),
        ),
    ]
